version: '1'
services: 
  yolo-db:
    image: mongo:5.0.16
    environment: 
      MONGO_DB: yolomy
    ports:
      - 27017:27017
  yolo-client:
    image: yolo-client_img:v1
    environment: 
      PORT: 3000
      PROXY_API: http://yolo-backend:5000/
    ports: 3000:3000
  yolo-backend:
    image: yolo-backend_img:v1
    environment: 
      MONGODB_URI: mongodb://yolo-db:27017/yolomy
    ports: 5000:5000
    
    