version: '3.3'
services: 
  yolo-db:
    image: mongo:5.0.16
    environment: 
      MONGO_DB: yolomy
    ports:
      - 2717:27017
    networks:
      - yolo-service
    volumes:
      - yolo-data:/etc/data/backend
  yolo-client:
    image: wanjikupatricia/yolo-client_img:v1.0.0.1
    environment: 
      PORT: 3000
      PROXY_API: http://yolo-backend:5000/
    ports: 
      - "3000:3000"
    networks:
      - yolo-service
    
  yolo-backend:
    image: wanjikupatricia/yolo-backend_img:v1.0.0.1
    environment: 
      MONGODB_URI: mongodb://yolo-db:27017/yolomy
    ports: 
      - "5000:5000"
    networks:
      - yolo-service
    
networks:
  yolo-service:
    driver: bridge
volumes:
  yolo-data:

    
