apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: yolo_backend
        image: wanjikupatricia/yolo-backend_img:v1.0.0.1
        ports:
        - containerPort: 5000
